### PR TITLE
Reading list support

### PR DESCRIPTION
**Pull request by cl3m**
Few change to support reading list bookmarks

### CODE REVIEW

**Comment by raszi** [comment]
@josh- are you planning to merge this?

**Comment by toddbluhm** [comment]
@josh- @cl3m  Any chance we could get this rebased and merged in? I would love to close down my fork. This PR is really the only reason my fork exists at this point. I still get stars on github for my fork, I would much rather point people to the official repo here where compatibility continues forward.

**Comment by dragz202** [comment]
CT 2.0 not picking up tabs on phone ... how to solve or debug?

**Comment by josh-** [comment]
Thanks so much for this awesome PR @cl3m! Super sorry I haven't merged this until now, but glad it's made it in 😄

I haven't included the ability to add Chrome tabs to the Reading List just yet – I want to quickly polish that up and add support for a few other browsers (if possible) but will do so soon 👍

**Pull request closed without merging**
