### PR TITLE
Add README section with workaround for macOS Mojavi start-up issue

### PR DESCRIPTION
**Pull request by OldhamMade**
This PR adds a `README` section with details on how to work around a recent issue with macOS 10.14 Mojave.

### CODE REVIEW

**Comment by OldhamMade** [comment]
@josh- nudge :)

**Comment by nickel715** [comment]
Amazing thanks for this hint, I had the same issue. Can this PR get merged please!

**Comment by ksbrar** [comment]
bump.

**Comment by josh-** [comment]
Thanks very much for your contribution @OldhamMade! I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which detects when Full Disk Access is required and prompts users to enable it inside the app.

Please let me know if you have feedback on the feature 😄

**Pull request closed without merging**
